### ISSUE TITLE
Decide on the platform for  MozFestEA

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#1]
Current live site :http://mozfestea.org/2015/

Site in dev : http://lawk.github.io/mozfestea-web/

**Comment by debloper** [comment]
## Static Site
- Pros:
  - Flexibility to almost anything related to UI/UX
  - Real easy deployment/updating
  - Very low maintenance
  - No dependency
- Cons:
  - No server side scripting (so no authentication, dynamic content)
  - Complex features can be emulated, but it gets... complex
  - Site content update becomes maintainers' task
  - Will take more time to go live

## WordPress Site
- Pros:
  - Social, Blog, CFP, Schedule and all dynamic contents
  - Design & content stays separate & doesn't block
  - All contents can be updated more easily
  - Less time to go live (theme existing)
- Cons:
  - Comes with the baggage of PHP & MySQL
  - Migrating is relatively tougher job
  - Needs proper maintenance

There's a ton of things I'm missing on both sides, but let's all chime in.

**Comment by Saallen** [comment]
Creating a deadline for this decision for the 17th of April at 1pm GMT/4PM EAT
Input required from @ThomasFarrow , @lawk , @jsan4christ and @elioqoshi -

**Comment by simeonoriko** [comment]
Happy to help with a Wordpress instance - content wise. If there's a ready theme, happy to go at it.

**Comment by lawk** [comment]
Current theme is WordPress

Regards,

Lawrence
Lead MozFestEA

Sent from mobile. Watching every step so I don't trip, please forgive any
typos.

**Comment by Saallen** [comment]
Word press is the platform moving forward- @lawk can you give everyone on this thread access to the admin site? I will work on copy now and in the meeting on Wednesday we can start tracking out the build :+1:

**Comment by lawk** [comment]
San James, Deb and Tom already have access.

I've just granted you and Simeon as well. Sarah you are now able to add any
other users I've missed :)

Thanks.

_Regards,_

_Lawrence_
_Lead MozFestEA_

**Comment by Saallen** [comment]
BOOM! Closing our first ticket \o/

**Comment by lawk** [comment]
Haha yey!

Regards,

Lawrence
Lead MozFestEA

Sent from mobile. Watching every step so I don't trip, please forgive any
typos.
