### ISSUE TITLE
Indiegogo campaign material : Lawrence Video

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#10]
Hey @lawk 
I got this video from Dosed for the Indiegogo campaign- I sent it to @SSJ2trunks. already.
I will add the link here for future use

http://we.tl/s5ObIdypBS

**Comment by lawk** [comment]
Thanks will take a look when I get to better bandwidth.

_Regards,_

_Lawrence_
_Lead MozFestEA_

**Comment by Saallen** [comment]
Is there a file to old MEA photos or flickr accounts we can access to use these photos?
Please add links here.

**Comment by lawk** [comment]
San James shared these with spencer but I don't know where he placed them
online.

Regards,

Lawrence
Lead MozFestEA

Sent from mobile. Watching every step so I don't trip, please forgive any
typos.

**Comment by Saallen** [comment]
@jsan4christ can you add them here when you get a chance?

**Comment by Saallen** [comment]
Where are we at with this piece? Are we ready to build the page?
Who is responsable for this peice too?

**Comment by SSJ2trunks** [comment]
I'm ready to finalize it if no other clips are being added.

3rd draft with minor changes:
https://www.youtube.com/watch?v=5kTJ2OGt8HA
