### ISSUE TITLE
Indiegogo campaign material; Video version

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#11]
Driver: @jsan4christ 
Project lead @SSJ2trunks
Decision maker @lawk @jsan4christ

**Comment by Saallen** [comment]
Version one of the campaign video
https://www.youtube.com/watch?v=MPa2XyDjx_Q

**Comment by lawk** [comment]
Look at San James' glow, lol. Video looks amazing, Spencer rocks, wow!!!

Regards,

Lawrence
Lead MozFestEA

Sent from mobile. Watching every step so I don't trip, please forgive any
typos.

**Comment by simeonoriko** [comment]
Very nice!

2 quick suggestions:
1. Use more pics of last years event
2. New branding

<3 it.

**Comment by jsan4christ** [comment]
Lawrence sent me the pictures to upload but for Spenser to use but they are
mostly corrupted.

On Sat, Apr 25, 2015 at 2:48 AM, Simeon Oriko notifications@github.com
wrote:

> Very nice!
> 
> 2 quick suggestions:
> 1. Use more pics of last years event
> 2. New branding
> 
> <3 it.
> On Apr 24, 2015 21:15, "Lawrence" <notifications@github.com> wrote:
> 
> > Look at San James' glow, lol. Video looks amazing, Spencer rocks, wow!!!
> > 
> > Regards,
> > 
> > Lawrence
> > Lead MozFestEA
> > 
> > Sent from mobile. Watching every step so I don't trip, please forgive any
> > typos.
> > On Apr 24, 2015 9:03 PM, "Saallen" notifications@github.com wrote:
> > 
> > > Version one of the campaign video
> > > https://www.youtube.com/watch?v=MPa2XyDjx_Q
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-96015824
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-96020660
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-96102811
> .

## 

San Emmanuel James
P. O. Box 7475,
Kampala, Uganda
Skype: jsan4christ

## Mobile: +256775955559, +256711955559

The Lord is my shepherd, I shall not want! Psalms 23

**Comment by SSJ2trunks** [comment]
For some reason, out of all the files San sent me, those are the only pictures i was able to see. All the other videos and photos were corrupted.  I only need about 10 photos, so can you guys please find 10 recent photos you guys would like me to use. Please compress everything into one folder first and send it to me. What other branding ideas, did you want me to change? I got a new logo Friday.

**Comment by lawk** [comment]
Hey,

I'm actually currently with James, we're getting you real good stuff. We'll
also send in the camera footage soon we've to copy it from the dvds we were
given, San's laptop has no dvd drive so I will be extracting them tonight.

Thanks for the patience and awesome work.

Regards,

Lawrence
Lead MozFestEA

**Comment by SSJ2trunks** [comment]
Again the videos and photos sent from Chris can not be opened.. maybe its a box issue. Do you guys have drop box?

**Comment by SSJ2trunks** [comment]
google drive

**Comment by lawk** [comment]
Hey Spencer,

San was still sending you the files but he ran out of space.... I advised
him to use Google Drive since our community drives have more than 30gb
space.

Also the new files being sent are working perfectly we checked them out.
The ones from Chris were taken by a lumia 1040 and for the videos please
click only those files that are jpeg and .mp4 I think.... Any other file in
the Chris folder is probably a system file.

Please bear with us until James finishes sending these through.

Thanks.

google drive

**Comment by jsan4christ** [comment]
This was already shared with Spencer on google drive.

On Mon, Apr 27, 2015 at 10:55 PM, Lawrence notifications@github.com wrote:

> Hey Spencer,
> 
> San was still sending you the files but he ran out of space.... I advised
> him to use Google Drive since our community drives have more than 30gb
> space.
> 
> Also the new files being sent are working perfectly we checked them out.
> The ones from Chris were taken by a lumia 1040 and for the videos please
> click only those files that are jpeg and .mp4 I think.... Any other file in
> the Chris folder is probably a system file.
> 
> Please bear with us until James finishes sending these through.
> 
> Thanks.
> 
> google drive
> 
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-96770009
> 
> 
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-96796588
> .

## 

San Emmanuel James
P. O. Box 7475,
Kampala, Uganda
Skype: jsan4christ

## Mobile: +256775955559, +256711955559

The Lord is my shepherd, I shall not want! Psalms 23

**Comment by SSJ2trunks** [comment]
I looked over the google drive you sent me, I pulled more pictures from that pile. In terms of video footage, do you guys have anything from the classrooms of someone giving a talk or some team work going on? Id like to replace more of the footage from UK mozfest as possible. I found a time lapse of Uganda and replaced the intro.

2nd draft:
https://www.youtube.com/watch?v=mAnCudI4D_o

**Comment by lawk** [comment]
Actually yes, I got some DVDs from San James but they're proving hard to
copy on the Mac I think I might have to use Windows and probably make ISO
copies.

Regards,

Lawrence
Lead MozFestEA

**Comment by lawk** [comment]
Wow just watched the video, awesome! I'm going to be shooting another one
minute video of mine soon with stuff related and in context with mozfestea
and will send it soon.

Thanks again, you're really great with video, you should give me a 101.

Regards,

Lawrence
Lead MozFestEA

**Comment by simeonoriko** [comment]
I really like this edit.

No further suggestions from me.

**Comment by jsan4christ** [comment]
It only gets betters,

I hope to have the video recording from last year later today from Lawrence
and I will share that too. It should have the kind of thing you need.

Cheers,
San James.

On Thu, Apr 30, 2015 at 8:12 AM, Simeon Oriko notifications@github.com
wrote:

> I really like this edit.
> 
> No further suggestions from me.
> 
> On Apr 30, 2015 02:56, "Lawrence" notifications@github.com wrote:
> 
> > Wow just watched the video, awesome! I'm going to be shooting another one
> > minute video of mine soon with stuff related and in context with
> > mozfestea
> > and will send it soon.
> > 
> > Thanks again, you're really great with video, you should give me a 101.
> > 
> > Regards,
> > 
> > Lawrence
> > Lead MozFestEA
> > On Apr 30, 2015 2:36 AM, "Lawrence Kisuuki" <lawrence@mozilla-uganda.org
> > 
> > wrote:
> > 
> > > Actually yes, I got some DVDs from San James but they're proving hard
> > > to
> > > copy on the Mac I think I might have to use Windows and probably make
> > > ISO
> > > copies.
> > > 
> > > Regards,
> > > 
> > > Lawrence
> > > Lead MozFestEA
> > > On Apr 30, 2015 2:34 AM, "SSJ2trunks" notifications@github.com
> > > wrote:
> > > 
> > > > I looked over the google drive you sent me, I pulled more pictures
> > > > from
> > > > that pile. In terms of video footage, do you guys have anything from
> > > > the
> > > > classrooms of someone giving a talk or some team work going on? Id
> > > > like
> > > > to
> > > > replace more of the footage from UK mozfest as possible. I found a
> > > > time
> > > > lapse of Uganda and replaced the intro.
> > > > 
> > > > 2nd draft:
> > > > https://www.youtube.com/watch?v=mAnCudI4D_o
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-97614217
> > 
> > > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-97616918
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-97664467
> .

## 

San Emmanuel James
P. O. Box 7475,
Kampala, Uganda
Skype: jsan4christ

## Mobile: +256775955559, +256711955559

The Lord is my shepherd, I shall not want! Psalms 23

**Comment by Saallen** [comment]
I love this version- great work @SSJ2trunks :100: 
Michelle suggested adding the website URL in the closing frame.

**Comment by SSJ2trunks** [comment]
@Saallen  is mozfestea.org/2015 the official URL?

**Comment by lawk** [comment]
@SSJ2trunks yes but even mozfestea.org points you to the same domain
currently ☺

Regards,

Lawrence
Lead MozFestEA

**Comment by SSJ2trunks** [comment]
@lawk thanks for doing that!  I think in terms of context we have enough.  What would make the video stronger would be adding in more B-roll footage of the community, people working together, someone giving a presentation, interaction with kids etc preferably video and not photos.

thanks

**Comment by SSJ2trunks** [comment]
@jsan4christ  is there a way you can rally up a group of people the more the better saying Thank you for your support.  I'd like to place that at the end of the video.

**Comment by lawk** [comment]
@SSJ2trunks hopefully we'll try to extract the local footage with the event
presentations and have them to you by Saturday, my Mac failed to extract
them so we'll try on James' machine. I hope we can still keep in a blend of
some of the UK footage like the people flooding because they have better
camera angles, also the end part with the several mozillians from summit...
beautiful!
About the support short footages, I spoke to @jsan4christ today and pitched
a similar idea...

@jsan4christ you think we could convince innovate at UrbanTV to run it
during their show? It's their kind of thing.

Thanks for all the help.

_Regards,_

_Lawrence_
_Lead MozFestEA_

**Comment by SSJ2trunks** [comment]
@lawk  keep in mind this video was made with the intent of it being watch on the indiegogo page, I'm worried if it was played outside of the website, will people still get its to raise money within indieigogo. I would just have UrbantTV mention to people can go to indiegogo and search mozfest EA or something along that line. Just have the fundraising page all setup before hand.

**Comment by lawk** [comment]
@SSJ2trunks it was just an idea and we can't promote before everything is
ready :)

_Regards,_

_Lawrence_
_Lead MozFestEA_

**Comment by SSJ2trunks** [comment]
I'm ready to call this video done unless there's anything that needed to be added or changed. 
Thanks

Preview:
https://www.youtube.com/watch?v=5kTJ2OGt8HA

Download link MP4:
https://www.dropbox.com/s/4b0d0ltyr4c0vqi/Mozfest%20EA.mp4?dl=0

**Comment by jsan4christ** [comment]
We can always supplement it with another, consider it done!

On Tue, May 19, 2015 at 8:23 PM, SSJ2trunks notifications@github.com
wrote:

> I'm ready to call this video done unless there's anything that needed to
> be added or changed.
> Thanks
> 
> Preview:
> https://www.youtube.com/watch?v=5kTJ2OGt8HA
> 
> Download link MP4:
> https://www.dropbox.com/s/4b0d0ltyr4c0vqi/Mozfest%20EA.mp4?dl=0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Saallen/MozFest-EastAfrica-Website/issues/11#issuecomment-103601188
> .

## 

San Emmanuel James
P. O. Box 7475,
Kampala, Uganda
Skype: jsan4christ

## Mobile: +256775955559, +256711955559

The Lord is my shepherd, I shall not want! Psalms 23

**Comment by Saallen** [comment]
:100: :+1:  \o/ Nice work team

**Comment by jsan4christ** [comment]
Hi Saallen/MozFest-East,

I'd like to add you to my professional network on LinkedIn.
- San Emmanuel

Confirm that you know San Emmanuel: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=repwrnDj&invitationId=6194127699989057536&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiufhpbh7%7Egc

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iufhpbh7-gc&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEY5XC8cxAPCwAAAVfX2ckpZFwogHTO-2zSadXSpDQaeDQWC7eYut_BPZmNXOI3HKx2xGXxYdMglS2EopDr7xjRlIs8XpeFJBkQ30vRHMCi2JH3RaDCagilJG1dk5tCDAXPXduvAo-MgxDwZ3G6JXwI70hqgntbjspculLxSXmpHoFGRrqmaBNztKp1FpfzpDgW&eid=0-iufhpbh7-gc

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iufhpbh7-gc&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
Hi Saallen/MozFest-East,

I'd like to add you to my professional network on LinkedIn.
- San Emmanuel

Confirm that you know San Emmanuel: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=0allNbE7&invitationId=6194127699921944576&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiufhpc71%7Ex3

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iufhpc71-x3&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEXVE4NeSPxSgAAAVfX2eCJh3xFEyNGiia4UmneL95N_LAyicg0zOdWKZ5kLAPvcvTnu63CCXc_2k_zIM5W6_XmKyL31OptIFZx66tayWaW7PRDgx6XUPRZdVjiqETVcH9usvenH4kGUcRm-6PNhOq1A0V1DwAKHRGg1FpO5WnGaC7p6rGbv97K3aQIDPTEqOoL&eid=0-iufhpc71-x3

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iufhpc71-x3&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
Join San Emmanuel James and over 300 million other professionals already on LinkedIn

Sign up to become San Emmanuel's newest connection.

Confirm that you know San Emmanuel: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=aTv2Xpf8&invitationId=6194127699770957824&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiufhpzuv%7Enj

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iufhpzuv-nj&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEdbWQdeAHLmAAAAVfX2kcHB2GPDkvVlezHH3TfqmAfIgCRIXEBRS6gq_5AkpTbKGQYm4RegKWZKD-5uVabe2j1oEBIiQyJI7g3bhkRR-GsNLXlB338DUlXLLrcHHHxaHUicuc4zSm3z0SM1t72yC4Vrgd_63sXXVjkwmqzpbS6JxnAyr9imGqPAmwwknP3NX-m&eid=0-iufhpzuv-nj

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iufhpzuv-nj&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
Hi Saallen/MozFest-East,

I'd like to add you to my professional network on LinkedIn.
- San Emmanuel

Confirm that you know San Emmanuel: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=U5bDOh2j&invitationId=6194127699653509122&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiufhqodc%7Ely

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iufhqodc-ly&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHfi7OBYxeXTwAAAVfX2slRwZYdailwOzVj60Q5r8Fk3N8zjd_3-5uqH_djZKGE2J6iF7S-nIAc39Dbtt1OxZqoh9QUi_l5EQpsLgDk1Qu8-kxi3eSpk2gLjv6o-ZsaYJyJMJLvj7mT_S4mXa3AftXsj2ZxGTWRRr6wKOB4uYC4h-i0l6OpeuQ0_p17OHP_rpmU&eid=0-iufhqodc-ly

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iufhqodc-ly&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=repwrnDj&invitationId=6194127699989057536&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7E1a2baj%7Eiuozp1c9%7Ej0

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=repwrnDj&invitationId=6194127699989057536&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E1a2baj%7Eiuozp1c9%7Ej0

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-1a2baj-iuozp1c9-j0&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-1a2baj-iuozp1c9-j0&loid=AQFyFK_tMXNRmAAAAVf7FOpaSc4eXu35McQcuMClzkfJwPxslvigxsy7DciqyRrDbDUdj5rNeI3ZD1H1LvfeMJjE9W1VJ1WTNLRTD0ygDleTba2jhrIBeO1DBVvJyIwmoktZjdVfwGzcjZJYYf_UTZ3SO_nJZrNAKz2IEtSJo_UDjRUqJvnx8Vy8GGy36sdhR5S3

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-1a2baj-iuozp1c9-j0&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=aTv2Xpf8&invitationId=6194127699770957824&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-uqfqrf%7Eiuozp4ry%7Ewq

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=aTv2Xpf8&invitationId=6194127699770957824&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-uqfqrf%7Eiuozp4ry%7Ewq

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=uqfqrf-iuozp4ry-wq&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=uqfqrf-iuozp4ry-wq&loid=AQENW1Zwjw2yxwAAAVf7Er4qz8Drj04F9woWLwyy26OpLnz03V3fCVQ97D1ThPbHRdfnaNg4mvYKxwcOL86tJWIylrWekZyD0PB8KneRDELkap5PQTcNVhood_dVPhIskBURkHJrBfzz0JzBI27LGyJMZ7bTv5dDzjr95_vxK7dwj4Rzoz6rR10sgRFgV4L8rHv7

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=uqfqrf-iuozp4ry-wq&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=U5bDOh2j&invitationId=6194127699653509122&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-qfwnb1%7Eiuozozxe%7Ex6

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=U5bDOh2j&invitationId=6194127699653509122&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-qfwnb1%7Eiuozozxe%7Ex6

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=qfwnb1-iuozozxe-x6&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=qfwnb1-iuozozxe-x6&loid=AQH2oFLGIDqYXQAAAVf7FroHfQCyKzr_x6KbVjJg5n20w606IGMJye2Zjy-xTiij_Nw74u0CvvPknzSnJHbkMLVVstPrFiTBFTfQNIB9eRD1pnd640ywgh1hrOuvigpKvjICvUjTQtKD_1v1jtg0t6GEP-WoGWHawKG54kkZIV4j76PAJbuN-Hg2OUYuePFR7oZh

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=qfwnb1-iuozozxe-x6&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=0allNbE7&invitationId=6194127699921944576&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Eq1urtl%7Eiuozpkn4%7Ek4

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=0allNbE7&invitationId=6194127699921944576&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eq1urtl%7Eiuozpkn4%7Ek4

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-q1urtl-iuozpkn4-k4&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-q1urtl-iuozpkn4-k4&loid=AQE8sE2VykIangAAAVf7FzKfw_PxlLlJYTSfL9HBAYGhC-JOfZmfrPnZSFaa0Kaqnse3QLnQxDAVB_QqnSKuww__WPTOrNC9W-XDxunbJwZ71lLFSrTE-Vgvlc21AyJ-WflmXL3BNTA9F55qIGqmVPg0bAOAO0GoG-DOKESjMUCxnCUuCXc92rn51voKVMZKkju3

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-q1urtl-iuozpkn4-k4&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
Hi ,

San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=aTv2Xpf8&invitationId=6194127699770957824&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-uqfqrf%7Eiuyzy7pb%7Ep1

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=aTv2Xpf8&invitationId=6194127699770957824&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-uqfqrf%7Eiuyzy7pb%7Ep1

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=uqfqrf-iuyzy7pb-p1&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=uqfqrf-iuyzy7pb-p1&loid=AQG0x5SDWLtdYwAAAVgfIAeLQQgiRIerZ4NTlRKUntSnpGsOf9kRGpqZyUmJm58TCL-z6LeArbck8Z3cGWjHXIrLR7rPLA_-9c2-quaqKyBgrL1D3I9KCSfKYx2b3_fStqDXHjhh6QeIQhXgIluuQPShkRy3BPOkBf72JjEDO73lyGU64Q4dR7PT0nOiOPtJHlSd

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=uqfqrf-iuyzy7pb-p1&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
Hi ,

San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=0allNbE7&invitationId=6194127699921944576&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Eq1urtl%7Eiuyzy7ri%7E8l

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=0allNbE7&invitationId=6194127699921944576&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Eq1urtl%7Eiuyzy7ri%7E8l

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-q1urtl-iuyzy7ri-8l&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-q1urtl-iuyzy7ri-8l&loid=AQF5c9Bej-wcRAAAAVgfIxqQ7DeaHn4DH8XLD4bmLgKK6B5-toQ2He0mxEPDDGD_O1plbRLbvGZd2yv_vdE_Ie5a1x1Q2Fk8wzBJbgWDhrqmjMZ4C79bzL9oCX5S8w-v9YPY7rxkkkl66Lv51pO63Hd7EjlMvlKX1BQhqoLtKgDMwh1EAxZrzxIfThV7SPRguC6y

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-q1urtl-iuyzy7ri-8l&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jsan4christ** [comment]
Hi ,

San Emmanuel James would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=U5bDOh2j&invitationId=6194127699653509122&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-qfwnb1%7Eiuyzy6ld%7Evc

View San Emmanuel James&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=U5bDOh2j&invitationId=6194127699653509122&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-qfwnb1%7Eiuyzy6ld%7Evc

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=qfwnb1-iuyzy6ld-vc&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=qfwnb1-iuyzy6ld-vc&loid=AQHWoqUdpesh6wAAAVgfKKtCQIDEFoGDIWRn8mnndtcHQPPKnEuv_03m2D3i67nTscmIl2SQD1x2SnBdmwx2_3CLdbAxXvl2nmEXqXQFyNcWxGnftWTr9SaZi5-xQKlhpbD_VQf8M8on2ggjyyeyY_KZnb_0lYmwunD1NkhXV8RmqoKLVrH_z8TlwBK0pKXQ5U0M

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=qfwnb1-iuyzy6ld-vc&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
