### ISSUE TITLE
How to get involved

### ISSUE THREAD

**Issue by jsan4christ** [Saallen/MozFest-EastAfrica-Website#12]
Please add the list of CTA you require on the How to get involved page
Lead @jsan4christ 
Support@ saallen + @mtotowajirani
Dev @debloper

**Comment by Saallen** [comment]
List of all CTA's
- Sign up on Eventbrite
- Submitt proposal
- Become a partner
  Am I missing any?

**Comment by Saallen** [comment]
[Copy]

 **How to get involved:**
The festival will take place over three days from the **17th -19th of July in Victoria University** [insert link for Uni location] and is open to all ages and abilities. The program will have something for all, from learning labs to club curriculum and developer sessions.

**Sign up on eventbrite** [insert link] and join us for a weekend of hacking, designing, peer learning and social innovation. Tickets are free and give you access to the event all weekend.

You can submit a **session** [insert link] to take place over the MEA festival weekend. You can facilitate more than one session or sessions from different tracks in which you have demonstrated expertise. To submit a session, visit our facilitators sign up page. All sessions submitted will be evaluated by the MEA team and a final list of accepted proposals will be listed on our site.

We have a lot of  **volunteer positions** available and need help in a variety of roles from Session leaders, to logistics and registration desk. If you want to get involved contact us here and tell us how you want to help

Are you a tech hub or incubator looking to help us shape the future of digital education and social innovation in East Africa. or a company who can help support the festival structure through sponsorship. **To support us financial**, visit our indiegogo campaign[insert link]. To support us in kind, visit our contacts page.
