### ISSUE TITLE
Call for proposals page 

### ISSUE THREAD

**Issue by simeonoriko** [Saallen/MozFest-EastAfrica-Website#13]
- [ ] Create call for proposals Wordpress Page Driver @debloper 
- [x] Write up a paragraph summarizing the Call for Proposals @mtotowajirani 
- [x] Add Google Docs iFrame @mtotowajirani

**Comment by Saallen** [comment]
@debloper have we made any progress here?

**Comment by Saallen** [comment]
@mtotowajirani - Did I imagine another issue around the Call for Proposals page? with links and text?
If not can you please link to this issue?
