### ISSUE TITLE
Subticket for Home page build - festival photo

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#14]
Add high res local picture for homepage of website @jsan4christ 
Can you add a good local festival picture which you might already have sourced for Indiegogo campaign?

**Comment by lawk** [comment]
I thought there was already one local pic?

Regards,

Lawrence
Lead MozFestEA

**Comment by Saallen** [comment]
There is a MozFest volunteer photo but we though it might be nice to have a local one for the main page.

**Comment by lawk** [comment]
oooh makes sense :)

_Regards,_

_Lawrence_
_Lead MozFestEA_

**Comment by Saallen** [comment]
Rookie mistake
https://www.youtube.com/watch?v=mAnCudI4D_o

On 30/04/2015 13:03, Lawrence wrote:
> oooh makes sense :)
>
>
>
> *Regards,*
>
> *Lawrence*
> *Lead MozFestEA*
>
> On Thu, Apr 30, 2015 at 12:02 PM, Saallen <notifications@github.com> 
> wrote:
>
> > There is a MozFest volunteer photo but we though it might be nice to 
> have
> > a local one for the main page.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/Saallen/MozFest-EastAfrica-Website/issues/14#issuecomment-97712721>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Saallen/MozFest-EastAfrica-Website/issues/14#issuecomment-97750269>.
>

-- 
Sarah Allen

Events Manager and MozFest Producer
Mozilla Foundation

**Comment by Saallen** [comment]
@jsan4christ do you have a picture we can use here?

**Comment by Saallen** [comment]
Sent email with 4 pictures options to @debloper

**Comment by arky** [comment]
@Saallen There are quite a few pictures in this flicker stream 

http://www.flickr.com/search/?w=all&q=MozFestEA

HTH

**Comment by debloper** [comment]
Used the pictures given by Sarah; and though indeed the flickr album has some nice clicks, I'd let you guys take the picks of which ones to include. I'll update the image slider likewise.
