### ISSUE TITLE
Eventbrite page link and copy

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#15]
@mtotowajirani
Can you add the eventbrite page link here ?

**Comment by simeonoriko** [comment]
http://mozfestea15.eventbrite.com

If anyone needs access to the backend I can add them on there as well. Just ping me about it.

**Comment by Saallen** [comment]
Text around this could simply be..
'Sign up for MozFestEast Africa on our eventbrite page. All tickets are free."

Thought?

**Comment by simeonoriko** [comment]
Yes, that works!

So there are 54 tickets left. Once those are sold out, I can open up about 200 more tickets. This ok with everyone?

**Comment by lawk** [comment]
Sounds good to me, I hope we can reach 800 people....

I'm liaising with MTN Telecom and they might bring students, chances are
high we're looking at a possible 200-500 student turn out on one of the
days.

Thanks

Regards,

Lawrence
Lead MozFestEA
