### ISSUE TITLE
Volunteer sign up form

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#16]
Please add the volunteer sign up form here with a call to action on why people should sign up @mtotowajirani and @jonathanM

**Comment by simeonoriko** [comment]
https://docs.google.com/forms/d/1MoW0KHdSTUzoVh7Nzz-IKLEmIYZWq6l8oZbukKAqkJg/viewform (Live form. I don’t have the link to the editable form. @jonathanM please share credentials for the editable version)
