### ISSUE TITLE
MEA: Enable Pretty URIs

### ISSUE THREAD

**Issue by arky** [Saallen/MozFest-EastAfrica-Website#18]
By default Wordpress uses URL's with '?' in them (https://codex.wordpress.org/Using_Permalinks#Default:_.22Ugly.22)

This is ugly and causes long term maintenance a nightmare. Just change it following these instructions.  

https://codex.wordpress.org/Settings_Permalinks_Screen

Ugly: http://mozilla-uganda.org/?page_id=32
Pretty: http://mozilla-uganda.org/contact-us/

**Comment by Saallen** [comment]
I am getting a broken link on Pretty....is that the point here with this example?

**Comment by arky** [comment]
@Saallen That's just an example.

**Comment by Saallen** [comment]
:+1:

**Comment by debloper** [comment]
Done. Closing.
