### ISSUE TITLE
Create Call for Proposals page

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#2]
How will this page look
- Will it be a google doc integrated into the webpage?
- Will the link bring you to another page?
- Will people submit a proposal via google doc?

**Comment by debloper** [comment]
We can have a "Submit Your Session" link on the header, that leads to a page, with Google form embedded in it. That can be an easy to achieve solution, yes.

**Comment by Saallen** [comment]
:candy:
