### ISSUE TITLE
MozFestEA -  Colours on the main page

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#23]
@debloper To check if the colours columns above are graphic colours and make changes to match the new logos.

**Comment by debloper** [comment]
The colors are updated according to the logo locors, please have a look & confirm.

**Comment by Saallen** [comment]
:boom:

**Comment by lawk** [comment]
Lol the explosion ^_^

_Regards,_

_Lawrence_
_Lead MozFestEA_
