### ISSUE TITLE
MEA: Home page Content

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#5]
Driver: @saallen
Editting support : @jsan4christ

**Comment by Saallen** [comment]
Titles for Home page
- What the festival is about
  - Date and Location
  - How to get involved

Anything missing?

**Comment by Saallen** [comment]
Adding potential copy for the homepage- 
please feel free to add/comment 
https://docs.google.com/a/mozilla.com/document/d/1B69uPvuEiIKJ19-e-_P8cm6bB1oPJiIuvxnNaVbSiAk/edit?usp=sharing

**Comment by Saallen** [comment]
Activiation @debloper 
Input @lawk @jsan4christ @mtotowajirani

**Comment by debloper** [comment]
Please put a marker/r+ here when the content is stable & ready to go live.
