### ISSUE TITLE
Logo Confirmation

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFest-EastAfrica-Website#9]
Hey @jsan4christ @lawk @elioqoshi 
there is two logos in circulation
![variations-03](https://cloud.githubusercontent.com/assets/10194015/7323476/c395f32c-eaa6-11e4-916d-b7cf61e69bb8.jpg)
and 
![screen shot 2015-04-24 at 17 25 14](https://cloud.githubusercontent.com/assets/10194015/7323512/fe70e52e-eaa6-11e4-85ca-b35ca967ade2.png)
I think for branding we should pick one and use it accross all media's.

**Comment by simeonoriko** [comment]
I've been using this one that @elioqoshi sent I think a week ago. 

![variations-01](https://cloud.githubusercontent.com/assets/389670/7323632/bcc052f6-eab8-11e4-8963-5c90ea25eb24.jpg)

There are a few more as well:

![variations-02](https://cloud.githubusercontent.com/assets/389670/7323643/e36af212-eab8-11e4-8d36-72cc64156913.jpg)
![variations-03](https://cloud.githubusercontent.com/assets/389670/7323644/e36df7dc-eab8-11e4-8410-8f555a466f6a.jpg)
![variations-04](https://cloud.githubusercontent.com/assets/389670/7323645/e370064e-eab8-11e4-852a-74095f62db82.jpg)
![variations-05](https://cloud.githubusercontent.com/assets/389670/7323646/e3711c1e-eab8-11e4-8648-b7341e9fac1b.jpg)

**Comment by lawk** [comment]
I think all work. And I also gave priority to the multi coloured one Simeon
has been using.

Regards,

Lawrence
Lead MozFestEA

Sent from mobile. Watching every step so I don't trip, please forgive any
typos.

**Comment by Saallen** [comment]
Nice- I really like these colourful ones, I just watched the video spencer sent through and it contained the old logo so its important we are consistant to build the brand.

**Comment by lawk** [comment]
I understand but at the time it was early for us to create one... we can
ask him to add it to embed the new one or we can find ways to work around
it...

_Regards,_

_Lawrence_
_Lead MozFestEA_

**Comment by Saallen** [comment]
Hey, we need the PNG versions of these logos for @debloper 
@elioqoshi can you supply these?

**Comment by Saallen** [comment]
Logos with deb and in MEA 15, logo  folder
